### ISSUE TITLE
Wrong avg price on trading pg realized and unrealized Pnl when multiple trades are done

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#1270]
Traded in Binary Market.  First I sell 1 shares @0.42.  Next I have 2 bids on the order book (1 share to buy at .395 and 1 share to buy at .375).  Another user sells me those 2 shares (in one trade).  My Fills show bought 1 share at each price (have same etherscan tx).  My positions calculates the avg price as 0.395 (instead of the avg of both shares which traded at the same time)....Timesstamps on the trade history and etherscan confirm both buys were done in one trade.  I would expect My Realized Pnl (which currently shows .025) to be 0.035, which is (.395+.375)/2=.385.....(0.42-0.385)=0.035 and my unrealized s/b (.385-.375)= -0.01 b/c my avg price is .385 and the last trade price is .375

![3-7bugtxhash](https://user-images.githubusercontent.com/41301809/53985242-22fbdd80-40e9-11e9-8c3c-53f874eaa1b4.jpg)

![3-7bug-fills](https://user-images.githubusercontent.com/41301809/53985267-2f803600-40e9-11e9-8f9a-7e530807dc89.jpg)

![3-7realizedbug-pos](https://user-images.githubusercontent.com/41301809/53985283-38710780-40e9-11e9-9891-5177b3826667.jpg)

**Comment by nuevoalex** [comment]
One of those trades is for closing your short position and so wont be included in the calculation of your average share acquisition price for your new long position.

Consider the case of if you had put in a buy at .1 and a buy at .9.

The .9 order will be taken first obviously and this will close out your short position at a loss of `.9 - .42 = .48`. At this point in time you have no position and a realized loss of `.48`

The .1 order is then taken (even if it happens to be the same transaction, this doesn't actually matter) and you now have 1 share in a long position you acquired for .1.

**Comment by nuevoalex** [comment]
Seeing that you actually have a position of 2 shares and there were _3_ buy orders I understand better where the confusion is coming from.

It appears the transaction order is wrong in the history since the .395 price trade occurred before the .375 trade(s). You can confirm this looking at the etherscan events as well.

**Comment by bthaile** [comment]
So you are saying initially the order looked correct and this was the breakdown.
realized is:
open: 1 @ 0.42 (cost is (1 - 0.42) * 1)  0.58 ETH
closed: 1 @ 0.3950 (result is (1 - 0.3950) * 1) 0.605 ETH
realized: 0.605 - 0.58 = `0.025 ETH`

Now if the two trades were reversed in trade order,
realized is:
open: 1 @ 0.42 (cost is (1 - 0.42) * 1)  0.58 ETH
closed: 1 @ 0.3750 (result is (1 - 0.3750) * 1) 0.625
realized: 0.625 - 0.58 = `0.045 ETH`

unrealized:
open 1 @ 0.395 (cost is (0.395 * 1) 0.395 ETH
open 1 @ 0.375 (cost is (0.375 * 1) 0.375 ETH
unrealized 0.375 - 0.395 = `-0.02 ETH`  (simplified the calculation since there is just 1 share)

**Comment by bthaile** [comment]
Market trading history needs to take logIndex into account when sorting trades.
also an issue for filled orders

testing using market id 0xe72d65e958f75e3fef3989ba17eccb550e9c20b8

**Comment by bthaile** [comment]
fixed, pushing to sneakpeak, @Chwy5 give it a look.
The market trading history should be in correct order and filled orders.

This fix also addressed https://github.com/AugurProject/augur/issues/1256

**Comment by Chwy5** [comment]
The market Trade History is in the correct order, but the Fills still shows up in the wrong order along with the last print (dot) on the price history chart

**Comment by Chwy5** [comment]
Fills, Market trading history and chart last price are all in the correct order - closing this ticket
