### ISSUE TITLE
Invalid outcome for scalar markets needs to be shown as a percentage

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur#5554]
For Scalar Markets (bc the range can be very different) we need to show The Invalid outcome as a % instead of a value of the range input.

When the invalid outcome is selected for trading:
The Order Ticket should display a % (instead of the $)

So if the Min and Max range were 27000 - 29000 and I want to bid 10% on invalid I currently would need to enter buy 10 shares at 27200.  We rather have them enter buy 10 shares at 10%. (since it is trading the % of the market settling as invalid).

Market cards need to show invalid as a % as well (like we do for Binary and Multiple Choice)

**Comment by bthaile** [comment]
Is this correct? 
1. only "trade" percentage for Invalid outcome for scalar markets
2a. show error in order form if price "percentage" is outside of 0 to 100. 

` Do we allow decimals? like 10.34 `
2b. error would say `percentage is used to trade Invalid, range 0 to 100`
2c. add `%` instead of DAI symbol

simulate trade:
 convert percentage to actual price, round down based on tickSize of market
 run simulate trade and show total trade cost. 

`What if they type in total trade cost? calculate percentage? `

a few clarification questions, @Chwy5

**Comment by Chwy5** [comment]
1) Yes
2a) Yes show error and No decimals
2b) Just add % after 100
2c) Yes change $ to %

Make Total Total trade value read only (no input....user must input price (in %) and quantity

**Comment by bthaile** [comment]
not clear how to calculate price given percentage by user. The percentage of scalar price range isn't guaranteed to be a valid price based on tickSize. 

Could round down based on user inputted percentage. I'd need the formula, it's not clear to me. 
UI code on this branch `add-percentage-scalar-invalid`

**Comment by Chwy5** [comment]
@bthaile what is status on this ticket.....Order ticket in ui does show percentage, but when I add in a percentage i get an error

![Screen Shot 2020-02-08 at 12.12.59 PM.png](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/38bbf7ea-ce30-44c9-9d38-7651ae163ad5)

**Comment by bthaile** [comment]
This has been addressed with new contracts. There are a few issue. I'll PR

But getting error when trying to create order
![image](https://user-images.githubusercontent.com/3970376/74206965-2a096500-4c43-11ea-8218-ff6fde014b3e.png)

**Comment by Chwy5** [comment]
Whats the status of this ticket....

I still have a problem entering a % in for a scalar market.....

I made Yankees Regular season wins in a season Min/Max range is 0-162.
I enter quantity 1 and percentage 10 or 11 and I get a message Price must be a multiple of 1 (my precision is set to 1)

**Comment by bthaile** [comment]
![image](https://user-images.githubusercontent.com/3970376/74856913-8554ea80-5308-11ea-9be7-c450d9fac1ad.png)

**Comment by Chwy5** [comment]
fixed -closing
