### ISSUE TITLE
Number of Participation tokens I own not updating until manual refresh

### ISSUE THREAD

**Issue by matt-bullock** [AugurProject/augur#5890]
When I purchase participation tokens on the disputing page I don't see the number update or get a toast/bell alert to notify me of my action. If I navigate to another page and come back the number still doesn't update.  The only way to get the number to update  is to do a manual browser refresh

**Comment by Chwy5** [comment]
fixed - closing

**Comment by matt-bullock** [comment]
@chwy this is still an issue for me - updates are still a block behind or require a manual refresh. Can you re-test looking at the users participation tokens here;

![image.png](https://images.zenhubusercontent.com/5c07af47035895308911c4c5/cdc257b2-e830-4935-bd41-849bdc5cefbf)

**Comment by Chwy5** [comment]
not working when retesting, but even refresh doesnt work....reopening until we can retest

**Comment by matt-bullock** [comment]
Tested again and now it's working. closing
