### ISSUE TITLE
Azure: build/watch-azure doesn't replace BUILD_AZURE env var in augur.js

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur#629]

**Comment by tinybike** [comment]
@kevinday this should be fixed with the recent changes to the build.  Can you verify?

**Comment by kevinday** [comment]
@tinybike I do see that augur.js is included in build.js now which is helpful, but the `process.env.BUILD_AZURE` coming from augur.js is still not being substituted with `true` like I would expect. In the meantime I am still just search/replacing `process.env.BUILD.AZURE` with `true` as part of my deployment.

**Comment by tinybike** [comment]
Replaced w/ env.json config file.
